const fs = require('fs');
const path = require('path');
const file = path.join(__dirname, 'crm-ui-api.js');
const backup = file + '.bak_aiinsight_' + Date.now();
let src = fs.readFileSync(file, 'utf8');
fs.writeFileSync(backup, src);

const newCode = [
  '',
  '// ---- Patch: analise agregada de resposta/continuidade + insight IA ----',
  'async function computeResponseAnalysis(fromDt, toDt) {',
  '  const [msgs] = await pool.query(',
  '    "SELECT conversation_id, direction, created_at FROM whatsapp_messages WHERE created_at BETWEEN ? AND ? ORDER BY conversation_id, created_at ASC",',
  '    [fromDt, toDt]',
  '  );',
  '  const byConv = {};',
  '  msgs.forEach(function(m){',
  '    if (!byConv[m.conversation_id]) byConv[m.conversation_id] = [];',
  '    byConv[m.conversation_id].push(m);',
  '  });',
  '  const hourBuckets = {};',
  '  for (let h = 0; h < 24; h++) hourBuckets[h] = { inbound: 0, responses: 0, sumResponseMin: 0, continued: 0, stalled: 0, unanswered: 0 };',
  '  let totalInbound = 0, totalAnswered = 0, totalContinued = 0, totalStalled = 0, totalUnanswered = 0, sumResponseMin = 0;',
  '',
  '  Object.keys(byConv).forEach(function(convId){',
  '    const list = byConv[convId];',
  '    for (let i = 0; i < list.length; i++) {',
  '      if (list[i].direction !== "in") continue;',
  '      const t = new Date(list[i].created_at).getTime();',
  '      const hourBr = new Date(t - BR_OFFSET_MS).getUTCHours();',
  '      totalInbound++;',
  '      hourBuckets[hourBr].inbound++;',
  '      let j = -1;',
  '      for (let k = i + 1; k < list.length; k++) {',
  '        if (list[k].direction === "out") { j = k; break; }',
  '      }',
  '      if (j === -1) {',
  '        totalUnanswered++;',
  '        hourBuckets[hourBr].unanswered++;',
  '        continue;',
  '      }',
  '      const tReply = new Date(list[j].created_at).getTime();',
  '      const responseMin = (tReply - t) / 60000;',
  '      totalAnswered++;',
  '      sumResponseMin += responseMin;',
  '      hourBuckets[hourBr].responses++;',
  '      hourBuckets[hourBr].sumResponseMin += responseMin;',
  '      let continued = false;',
  '      for (let k = j + 1; k < list.length; k++) {',
  '        if (list[k].direction === "in") { continued = true; break; }',
  '      }',
  '      if (continued) { totalContinued++; hourBuckets[hourBr].continued++; }',
  '      else { totalStalled++; hourBuckets[hourBr].stalled++; }',
  '    }',
  '  });',
  '',
  '  const byHour = [];',
  '  for (let h = 0; h < 24; h++) {',
  '    const b = hourBuckets[h];',
  '    byHour.push({',
  '      hour: h,',
  '      inbound: b.inbound,',
  '      avgResponseMin: b.responses ? Math.round((b.sumResponseMin / b.responses) * 10) / 10 : null,',
  '      continued: b.continued,',
  '      stalled: b.stalled,',
  '      unanswered: b.unanswered',
  '    });',
  '  }',
  '',
  '  return {',
  '    byHour: byHour,',
  '    totals: {',
  '      conversations: Object.keys(byConv).length,',
  '      inboundMessages: totalInbound,',
  '      answered: totalAnswered,',
  '      unanswered: totalUnanswered,',
  '      continued: totalContinued,',
  '      stalled: totalStalled,',
  '      avgResponseMin: totalAnswered ? Math.round((sumResponseMin / totalAnswered) * 10) / 10 : null',
  '    }',
  '  };',
  '}',
  '',
  "app.get('/api/crm/ui/dashboard/sdrs/response-analysis', auth, async (req, res) => {",
  '  try {',
  '    const from = req.query.from || brTodayStr();',
  '    const to = req.query.to || brTodayStr();',
  '    const { fromDt, toDt } = brRangeToUtc(from, to);',
  '    const analysis = await computeResponseAnalysis(fromDt, toDt);',
  '    res.json({ success: true, analysis: analysis });',
  '  } catch (e) {',
  "    console.error('sdrs response-analysis error', e.message);",
  '    res.status(500).json({ success: false, error: e.message });',
  '  }',
  '});',
  '',
  'const __aiInsightCache = {};',
  "app.get('/api/crm/ui/dashboard/sdrs/ai-insight', auth, async (req, res) => {",
  '  try {',
  '    const from = req.query.from || brTodayStr();',
  '    const to = req.query.to || brTodayStr();',
  "    const cacheKey = from + '|' + to;",
  '    const cached = __aiInsightCache[cacheKey];',
  '    if (cached && (Date.now() - cached.ts) < 30 * 60 * 1000) {',
  '      return res.json({ success: true, insight: cached.insight, cached: true });',
  '    }',
  '    const { fromDt, toDt } = brRangeToUtc(from, to);',
  '',
  '    const analysis = await computeResponseAnalysis(fromDt, toDt);',
  '',
  '    const [callRows] = await pool.query(',
  '      "SELECT HOUR(DATE_SUB(a.created_at, INTERVAL 3 HOUR)) AS hourBr, COUNT(*) AS cnt " +',
  '      "FROM activities a WHERE a.type = \'Ligação Atendida\' AND a.created_at BETWEEN ? AND ? " +',
  '      "GROUP BY hourBr",',
  '      [fromDt, toDt]',
  '    );',
  '',
  '    const [convRow] = await pool.query(',
  '      "SELECT MIN(created_at) AS minD, MAX(created_at) AS maxD FROM whatsapp_messages WHERE created_at BETWEEN ? AND ?",',
  '      [fromDt, toDt]',
  '    );',
  '    const minD = convRow && convRow[0] && convRow[0].minD;',
  '    const maxD = convRow && convRow[0] && convRow[0].maxD;',
  '    const daysOfHistory = (minD && maxD) ? Math.max(1, Math.ceil((new Date(maxD) - new Date(minD)) / 86400000) + 1) : 0;',
  '',
  '    const topInboundHours = analysis.byHour',
  '      .filter(function(h){ return h.inbound > 0; })',
  '      .sort(function(a,b){ return b.inbound - a.inbound; })',
  '      .slice(0, 5)',
  "      .map(function(h){ return h.hour + 'h (' + h.inbound + ' msgs)'; })",
  "      .join(', ');",
  '',
  '    const topCallHours = (callRows || [])',
  '      .sort(function(a,b){ return b.cnt - a.cnt; })',
  '      .slice(0, 5)',
  "      .map(function(r){ return r.hourBr + 'h (' + r.cnt + ' ligações)'; })",
  "      .join(', ');",
  '',
  '    const slowHours = analysis.byHour',
  '      .filter(function(h){ return h.avgResponseMin !== null; })',
  '      .sort(function(a,b){ return b.avgResponseMin - a.avgResponseMin; })',
  '      .slice(0, 5)',
  "      .map(function(h){ return h.hour + 'h (' + h.avgResponseMin + ' min)'; })",
  "      .join(', ');",
  '',
  '    const context = [',
  "      'Período analisado: ' + from + ' a ' + to + '.',",
  "      'Amostra de WhatsApp: ' + daysOfHistory + ' dias de histórico, ' + analysis.totals.conversations + ' conversas, ' + analysis.totals.inboundMessages + ' mensagens recebidas de leads.',",
  "      'Horários de pico de mensagens recebidas (leads): ' + (topInboundHours || 'sem dados suficientes') + '.',",
  "      'Horários de pico de ligações atendidas: ' + (topCallHours || 'sem dados suficientes') + '.',",
  "      'Tempo médio de resposta da equipe: ' + (analysis.totals.avgResponseMin !== null ? analysis.totals.avgResponseMin + ' minutos' : 'sem dados suficientes') + '.',",
  "      'Horários com resposta mais lenta: ' + (slowHours || 'sem dados suficientes') + '.',",
  "      'Do total de ' + analysis.totals.answered + ' mensagens respondidas, ' + analysis.totals.continued + ' tiveram continuidade da conversa (lead respondeu de novo) e ' + analysis.totals.stalled + ' pararam após a resposta da equipe (lead não respondeu mais).',",
  "      'Mensagens de leads que nunca receberam resposta da equipe: ' + analysis.totals.unanswered + '.'",
  "    ].join('\\n');",
  '',
  "    const systemPrompt = 'Você é um especialista em inbound marketing e em agendamentos para clínicas de estética facial e odontologia high-ticket. Você está analisando os dados operacionais reais de uma clínica (Vivera Orofacial) para o dono do negócio. Escreva uma análise estratégica em texto corrido, em português do Brasil, com tom consultivo e direto (não seja uma lista fria de tópicos, escreva como uma leitura de especialista). Comente os horários de pico de entrada de mensagens e de ligações atendidas, relacione isso com o tempo de resposta da equipe, e comente se há indício de que demora na resposta está associada a conversas que morrem (lead para de responder). Dê recomendações práticas de estratégia (ex: escalas de horário, alertas de resposta rápida, priorização). Se a amostra de dados for pequena (poucos dias de histórico), deixe isso explícito no texto e module a confiança das conclusões de acordo — não afirme padrões fortes com poucos dados. Não invente números que não foram fornecidos.';",
  '',
  '    const apiKey = process.env.OPENAI_API_KEY;',
  '    let insightText = null;',
  '    if (apiKey) {',
  "      const resp = await fetch('https://api.openai.com/v1/chat/completions', {",
  "        method: 'POST',",
  "        headers: { 'Content-Type': 'application/json', 'Authorization': 'Bearer ' + apiKey },",
  '        body: JSON.stringify({',
  "          model: process.env.OPENAI_MODEL || 'gpt-4o-mini',",
  '          messages: [',
  "            { role: 'system', content: systemPrompt },",
  "            { role: 'user', content: 'Dados agregados:\\n' + context + '\\n\\nEscreva a análise agora.' }",
  '          ],',
  '          temperature: 0.4',
  '        })',
  '      });',
  '      const data = await resp.json();',
  '      insightText = data && data.choices && data.choices[0] && data.choices[0].message && data.choices[0].message.content;',
  '    }',
  '    if (!insightText) {',
  "      insightText = 'Não foi possível gerar a análise por IA no momento. Dados agregados:\\n' + context;",
  '    }',
  '',
  '    __aiInsightCache[cacheKey] = { insight: insightText, ts: Date.now() };',
  '    res.json({ success: true, insight: insightText, cached: false, stats: { analysis: analysis, topInboundHours: topInboundHours, topCallHours: topCallHours, daysOfHistory: daysOfHistory } });',
  '  } catch (e) {',
  "    console.error('sdrs ai-insight error', e.message);",
  '    res.status(500).json({ success: false, error: e.message });',
  '  }',
  '});',
  ''
].join('\n');

const marker = /\n\};\s*$/;
if (!marker.test(src)) {
  console.error('MARKER_NOT_FOUND');
  process.exit(1);
}
src = src.replace(marker, '\n' + newCode + '\n};\n');
fs.writeFileSync(file, src);
console.log('OK backend ai-insight patched, backup at ' + backup);
